# dataset setting
data_name: 'SUN'
data_root: './data/xlsa17/data'

# i/o setting
result: './result/sun'
ckpt_dir: './data/checkpoints/gdan_sun'
vae_dir: './data/checkpoints/cvae_sun/'
vae_ckpt: './data/checkpoints/cvae_sun/cvae_320.pkl'
best_checkpoint: 'gdan_50.pkl'

# flags and environment
gpu: '1'
debug: False

# evaluation
num_samples: 500
K: 1
classifier: 'knn'
C: 10.1

# optimizer setting
epoch: 500
batch: 128
steps: -1
learning_rate: 0.00001
g_iter: 1
d_iter: 1

# model setting
s_dim: 102
x_dim: 2048
z_dim: 100

enc: '1200 600'
dec: '600'
reg: '512'
dis: '800'

theta1: 0.1
theta2: 0.1
theta3: 0.1
